"""Canonical model set — import every model module so metadata is complete."""
from app.models import (
    audit,
    career,
    communication,
    company,
    documents,
    governance,
    identity,
    platform,
    privacy,
    talent,
    tenancy,
    work,
)
from app.models.company import (
    CompanyProfile,
    DocumentRequest,
    InterviewScorecard,
    JobPosting,
    ScreeningResponse,
)
from app.models.career import (
    ApplicationEvent,
    CareerGoal,
    CareerMilestone,
    Interview,
    JobApplication,
    Offer,
    Opportunity,
    OpportunityInteraction,
    UserNotification,
    WorkDnaAnswer,
    WorkDnaProfile,
)
from app.models.audit import AuditLogEntry
from app.models.communication import (
    Conversation,
    ConversationMessage,
    ConversationReadState,
    OutreachBlock,
    OutreachRequest,
)
from app.models.governance import (
    GovernanceCaseLink,
    GovernanceReport,
    GovernanceReportNote,
    GovernanceTeam,
    GovernanceTeamMember,
)
from app.models.platform import (
    NotificationPreference,
    PlatformEvent,
    RateLimitHit,
)
from app.models.documents import DocumentAccessGrant, PersonDocument
from app.models.identity import (
    EmailVerificationToken,
    PasswordResetToken,
    PersonProfile,
    RefreshToken,
    TimestampMixin,
    User,
)
from app.models.privacy import Consent, PersonVisibilitySetting
from app.models.tenancy import (
    ROLE_SUPER_ADMIN,
    Membership,
    Organization,
    Permission,
    Role,
    RolePermission,
)
from app.models.talent import (
    CandidateSearchEvent,
    CareerPath,
    CareerPathStep,
    OpportunityRequirement,
    SavedCandidate,
    SkillAlias,
    SkillEvidence,
    SkillRelationship,
    TalentPool,
    TalentPoolMember,
)
from app.models.work import (
    Credential,
    Education,
    Employment,
    Skill,
    UserSkill,
    WorkExperience,
)

__all__ = [
    "ApplicationEvent",
    "AuditLogEntry",
    "CandidateSearchEvent",
    "Conversation",
    "ConversationMessage",
    "ConversationReadState",
    "CareerGoal",
    "CareerMilestone",
    "CareerPath",
    "CareerPathStep",
    "CompanyProfile",
    "Consent",
    "Credential",
    "OpportunityRequirement",
    "DocumentAccessGrant",
    "DocumentRequest",
    "Education",
    "EmailVerificationToken",
    "Employment",
    "GovernanceCaseLink",
    "GovernanceReport",
    "GovernanceReportNote",
    "GovernanceTeam",
    "GovernanceTeamMember",
    "Interview",
    "InterviewScorecard",
    "JobApplication",
    "JobPosting",
    "Membership",
    "NotificationPreference",
    "Offer",
    "Opportunity",
    "OpportunityInteraction",
    "Organization",
    "OutreachBlock",
    "OutreachRequest",
    "PasswordResetToken",
    "Permission",
    "PersonDocument",
    "PersonProfile",
    "PersonVisibilitySetting",
    "PlatformEvent",
    "RateLimitHit",
    "RefreshToken",
    "Role",
    "RolePermission",
    "SavedCandidate",
    "ScreeningResponse",
    "Skill",
    "SkillAlias",
    "SkillEvidence",
    "SkillRelationship",
    "TalentPool",
    "TalentPoolMember",
    "TimestampMixin",
    "User",
    "UserNotification",
    "UserSkill",
    "WorkDnaAnswer",
    "WorkDnaProfile",
    "WorkExperience",
    "ROLE_SUPER_ADMIN",
]
